name: 'Docker build'

on:
  push:
    branches:
      - main

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: write
  pull-requests: write

# env:
#   BRANCH: ${{github.ref_name}}

jobs:
  docker-build:
    name: 'Docker build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checking out the repo

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: custom-errors # Provide Docker image name
          